// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	domain "todo-app/domain"
	clients "todo-app/pkg/clients"

	mock "github.com/stretchr/testify/mock"
)

// ItemRepo is an autogenerated mock type for the ItemRepo type
type ItemRepo struct {
	mock.Mock
}

// Delete provides a mock function with given fields: filter
func (_m *ItemRepo) Delete(filter map[string]interface{}) error {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(map[string]interface{}) error); ok {
		r0 = rf(filter)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: filter, paging
func (_m *ItemRepo) GetAll(filter map[string]interface{}, paging *clients.Paging) ([]domain.Item, error) {
	ret := _m.Called(filter, paging)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(map[string]interface{}, *clients.Paging) ([]domain.Item, error)); ok {
		return rf(filter, paging)
	}
	if rf, ok := ret.Get(0).(func(map[string]interface{}, *clients.Paging) []domain.Item); ok {
		r0 = rf(filter, paging)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(map[string]interface{}, *clients.Paging) error); ok {
		r1 = rf(filter, paging)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetItem provides a mock function with given fields: filter
func (_m *ItemRepo) GetItem(filter map[string]interface{}) (domain.Item, error) {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for GetItem")
	}

	var r0 domain.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(map[string]interface{}) (domain.Item, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(map[string]interface{}) domain.Item); ok {
		r0 = rf(filter)
	} else {
		r0 = ret.Get(0).(domain.Item)
	}

	if rf, ok := ret.Get(1).(func(map[string]interface{}) error); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: _a0
func (_m *ItemRepo) Save(_a0 *domain.ItemCreation) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.ItemCreation) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: filter, _a1
func (_m *ItemRepo) Update(filter map[string]interface{}, _a1 *domain.ItemUpdate) error {
	ret := _m.Called(filter, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(map[string]interface{}, *domain.ItemUpdate) error); ok {
		r0 = rf(filter, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewItemRepo creates a new instance of ItemRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewItemRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *ItemRepo {
	mock := &ItemRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
